version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

build:
  image: latest
  os: ubuntu-22.04
  commands:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/source docs/_build/html
