version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  commands:
  - pip install -r docs/requirements.txt
  - pip install .
  - sphinx-build -b html docs/source "$READTHEDOCS_OUTPUT/html"

